@startuml

package "Poet Assistant Server"  {
  package "endpoints" <<Cloud>> {
    object api.model
    object api
  }
  package "business logic" {
    object service.model
    object service
  }
  package "persistence" <<Database>> {
    object repository.entity
    object repository
  }
  
  api --> service
  service --> repository
}

@endpuml
