const val dependencyGraphGenerator = "0.6.0"
const val springDocVersion = "1.5.12"
const val sqliteDialectVersion = "0.1.2"
const val sqliteJdbcVersion = "3.36.0.3"
const val swaggerCodeGenVersion = "3.0.28"
